wx:
  mp:
    configs:
      - appId: wx39a57465e542c815
        secret: 2e8c1c05cf833250ab1888c0113e1c1d
        token: lovemyrm13
        aesKey: 20PQmo8xLWk0onA9uP9DGrNwrbONBpZivu45NOjqFdh
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    max-threads: 100
  servlet:
    context-path: /snmt/wx
spring:
  application:
    name: wx-mp-server
