hello: application
logging:
  level:
    org:
      springframework:
        retry: debug
    com:
      rm13:
        cloud:
          feign: debug

feign:
  okhttp:
    enabled: false
  httpclient:
    enabled: false
  # 开启熔断
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      fallback:
        # fallback 隔离，采用信号量模式，最大并发执行数1000
        isolation:
          semaphore:
            maxConcurrentRequests: 1000
      circuitBreaker:
        # 开启熔断
        enabled: true
        # 熔断窗口起5秒， 5秒后 open-> half-open -> close
        sleepWindowInMilliseconds: 5000
        # 错误比例 50%
        errorThresholdPercentage: 50

      execution:
        timeout:
          # 请求超时是否开启
          enabled: true
        isolation:
          # 请求采用线程池隔离模式， 超过5秒中，请求超时， 执行fallback
          thread:
            timeoutInMilliseconds: 5000


server:
  servlet:
    session:
      timeout: 30

management:
  endpoint:
    health:
      show-details: always


  endpoints:
    web:
      exposure:
        include: "*"



person:
  name: ylove
  password: yrm13
  detail1:
    - aa: yrm13
      bb: yrm13
    - aa: yrm14
      bb: yrm14
  addr1: [a1,b1,c1,d1]
  addr2: a2,b2,c2,d2
  addr3:
    - a3
    - b3
    - c3
    - d3
  user1:
    name: cc
    age: 18
  user2: {name: cc, age: 18}
  detail2: [{aa: a2, bb: b2},{aa: a3, bb: b3}]

