hello: application


logging:
  level:
    com:
      rm13:
        cloud:
          feign: debug

feign:
  okhttp:
    enabled: false
  httpclient:
    enabled: false

  hystrix:
    enabled: true

hystrix:
  command:
    default:
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 1000
      circuitBreaker:
        enabled: true
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50

      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000


server:
  servlet:
    session:
      timeout: 30

management:
  endpoint:
    health:
      show-details: always


  endpoints:
    web:
      exposure:
        include: "*"