hello: application


logging:
  level:
    com:
      rm13:
        cloud:
          feign: debug

feign:
  okhttp:
    enabled: true

server:
  servlet:
    session:
      timeout: 30

management:
  endpoint:
    health:
      show-details: always


  endpoints:
    web:
      exposure:
        include: "*"